theme: jekyll-theme-minimal
default_lang: en
languages: ['en', 'fr','de']
excerpt_separator: <!-- more -->
exclude: [d3/]
collections:
  audiopost:
    output: true
    permalink: /u/:path/
  stories:
    sort_by: sort
