title: Popkult60
email: c2dh.exhibitions@uni.lu
description: 'Popkult60 "Transnational popular culture - Europe in the long 1960s" is supported by the Deutsche Forschungsgemeinschaft (DFG) in Germany and the National Research Fund (FNR) in Luxembourg.'
theme: minima
default_lang: en
languages: ['en', 'fr','de']
excerpt_separator: <!-- more -->
exclude:
  - d3/
  - vendor/
  - tmp/
  - gems/
collections:
  audiopost:
    output: true
    permalink: /u/:path/
  stories:
    sort_by: sort
absolute_base_url: "https://popkult60.eu"
